default_env: "local"

# 数据库配置
# local 环境使用配置文件，其他环境从环境变量读取
environments:
  local:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "123666"
    dbname: "postgres"
    sslmode: "disable"
    timezone: "UTC"

# 表配置
tables:
  output_table_prefix: "GameResults_"
  data_num: 10000 # 目标数据量
  data_table_num: 10 # 每个RTP档位生成的数据表数量
  data_table_num_3: 5 # V3模式每个RTP档位生成的数据表数量
  data_num_fb: 4000 # FB模式目标数据量
  data_table_num_fb: 1 # FB模式每个RTP档位生成的数据表数量
  source_table_prefix: "GameResultData_"

# 性能优化配置
settings:
  log_level: "info"
  batch_size: 1000
  timeout: 30
  s3_import:
    max_concurrency: 1 # S3导入最大并发数
    batch_size: 2000 # S3导入批处理大小
    buffer_size: 8192 # 缓冲区大小
  database:
    max_open_conns: 25 # 最大打开连接数
    max_idle_conns: 10 # 最大空闲连接数
    conn_max_lifetime: 0 # 连接最大生存时间(分钟) - 0表示无限制
    conn_max_idle_time: 10 # 连接最大空闲时间(分钟) - 延长到10分钟
    ping_interval: 5 # 连接健康检查间隔(分钟) - 延长到5分钟

# 游戏配置
game:
  id: 1513328
  bl: 20.0
  isFb: true

# 投注配置
bet:
  cs: 1.0 # 硬币面值
  ml: 1.0 # 投注线数倍数
  bl: 20.0 # 投注线数
  fb: 75 # 购买夺宝的倍数

# 奖品比例配置
prize_ratios:
  big_prize: 0.01 # 大奖比例
  mega_prize: 0.005 # 巨奖比例
  super_mega_prize: 0.001 # 超级巨奖比例

# 阶段比例配置
stage_ratios:
  stage1_min_ratio: 0.6 # 第一阶段最小比例
  stage1_max_ratio: 0.8 # 第一阶段最大比例
  stage3_win_top_ratio: 0.9 # 第三阶段大额补齐比例
  upper_deviation: 0.005 # 允许上偏差

# Multi-Game Configuration (多游戏配置)
multi_game:
  enabled: false # 是否启用多游戏模式
  games:
    - id: 1513328
      bl: 20
      isFb: true
    # - id: 103
    #   bl: 50
    #   isFb: false
    # - id: 105
    #   bl: 30
    #   isFb: true

# S3 Configuration (S3配置)
s3:
  enabled: true # 是否启用S3导入功能
  bucket: "mpg-rtp-data"
  region: "ap-east-1"
  access_key_id: "YOUR_AWS_ACCESS_KEY_ID"
  secret_access_key: "YOUR_AWS_SECRET_ACCESS_KEY"
  normal_prefix: "mpg-slot-data" # 普通模式路径前缀
  fb_prefix: "mpg-slot-data" # 购买夺宝模式路径前缀
