default_env: "local"

# 数据库配置
environments:
  local:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "123666"
    dbname: "postgres"
    sslmode: "disable"
    timezone: "UTC"
  hk-test:
    host: "hk-test-db.example.com"
    port: 5432
    user: "postgres"
    password: "test_password"
    dbname: "filtering_data"
    sslmode: "require"
  br-test:
    host: "br-test-db.example.com"
    port: 5432
    user: "postgres"
    password: "test_password"
    dbname: "filtering_data"
    sslmode: "require"
  br-prod:
    host: "br-prod-db.example.com"
    port: 5432
    user: "postgres"
    password: "prod_password"
    dbname: "filtering_data"
    sslmode: "require"
  us-prod:
    host: "us-prod-db.example.com"
    port: 5432
    user: "postgres"
    password: "prod_password"
    dbname: "filtering_data"
    sslmode: "require"
  hk-prod:
    host: "hk-prod-db.example.com"
    port: 5432
    user: "postgres"
    password: "prod_password"
    dbname: "filtering_data"
    sslmode: "require"

# 表配置
tables:
  output_table_prefix: "game_results_"
  source_table_prefix: "GameResultData_"

# 性能优化配置
settings:
  log_level: "info"
  batch_size: 1000
  timeout: 30
  s3_import:
    max_concurrency: 12 # S3导入最大并发数
    batch_size: 2000 # S3导入批处理大小
    buffer_size: 8192 # 缓冲区大小
  database:
    max_open_conns: 25 # 最大打开连接数
    max_idle_conns: 10 # 最大空闲连接数
    conn_max_lifetime: 0 # 连接最大生存时间(分钟) - 0表示无限制
    conn_max_idle_time: 10 # 连接最大空闲时间(分钟) - 延长到10分钟
    ping_interval: 5 # 连接健康检查间隔(分钟) - 延长到5分钟

# 游戏配置
game:
  id: 1513328
  bl: 20.0
  isFb: true

# Multi-Game Configuration (多游戏配置)
multi_game:
  enabled: false # 是否启用多游戏模式
  games:
    - id: 1513328
      bl: 20
      isFb: true
    # - id: 103
    #   bl: 50
    #   isFb: false
    # - id: 105
    #   bl: 30
    #   isFb: true

# S3 Configuration (S3配置)
s3:
  enabled: false # 是否启用S3导入功能
  bucket: "mpg-rtp-data"
  region: "ap-east-1"
  access_key_id: "YOUR_AWS_ACCESS_KEY_ID"
  secret_access_key: "YOUR_AWS_SECRET_ACCESS_KEY"
  normal_prefix: "mpg-slot-data" # 普通模式路径前缀
  fb_prefix: "mpg-slot-data" # 购买夺宝模式路径前缀
