# RTP档位倍率分布配置文件
rtp_multiplier_distribution:
  # 档位 1 (总RTP: 0.6)
  rtp_1:
    rtp_no: 1
    rtp_value: 0.6
    # RTP组成
    rtp_components:
      normal_rtp: 0.5 # 普通玩法RTP
      special_rtp: 0.1 # 特殊玩法RTP (购买夺宝等)
    multiplier_distribution:
      zero_win: 0.7607 # 0倍 (不中奖) 占比 75%
      low_multiplier: 0.1214 # 0-1倍 占比 20%
      medium_multiplier: 0.091 # 1-5倍 占比 4%
      high_multiplier: 0.0191 # 5-10倍 占比 0.8%
      very_high_multiplier: 0.0078 # 10-20倍 占比 0.2%
      mega_multiplier: 0.0 # 20-50倍 占比 0%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 2 (总RTP: 0.7)
  rtp_2:
    rtp_no: 2
    rtp_value: 0.7
    rtp_components:
      normal_rtp: 0.6 # 普通玩法RTP
      special_rtp: 0.1 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.7607 # 0倍 (不中奖) 占比 75%
      low_multiplier: 0.1214 # 0-1倍 占比 20%
      medium_multiplier: 0.091 # 1-5倍 占比 4%
      high_multiplier: 0.0191 # 5-10倍 占比 0.8%
      very_high_multiplier: 0.0078 # 10-20倍 占比 0.2%
      mega_multiplier: 0.0 # 20-50倍 占比 0%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 3 (总RTP: 0.75)
  rtp_3:
    rtp_no: 3
    rtp_value: 0.75
    rtp_components:
      normal_rtp: 0.60 # 普通玩法RTP
      special_rtp: 0.15 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 68%
      low_multiplier: 0.1132 # 0-1倍 占比 24%
      medium_multiplier: 0.0851 # 1-5倍 占比 6%
      high_multiplier: 0.0190 # 5-10倍 占比 1.5%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.4%
      mega_multiplier: 0.0067 # 20-50倍 占比 0.1%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 4 (总RTP: 0.8)
  rtp_4:
    rtp_no: 4
    rtp_value: 0.8
    rtp_components:
      normal_rtp: 0.6 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 65%
      low_multiplier: 0.1121 # 0-1倍 占比 26%
      medium_multiplier: 0.0851 # 1-5倍 占比 7%
      high_multiplier: 0.0190 # 5-10倍 占比 1.5%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.4%
      mega_multiplier: 0.0077 # 20-50倍 占比 0.1%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 5 (总RTP: 0.85)
  rtp_5:
    rtp_no: 5
    rtp_value: 0.85
    rtp_components:
      normal_rtp: 0.65 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.78 # 0倍 占比 62%
      low_multiplier: 0.1025 # 0-1倍 占比 28%
      medium_multiplier: 0.091 # 1-5倍 占比 8%
      high_multiplier: 0.0133 # 5-10倍 占比 1.5%
      very_high_multiplier: 0.0063 # 10-20倍 占比 0.4%
      mega_multiplier: 0.0069 # 20-50倍 占比 0.1%
      super_mega_multiplier: 0.0010 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 6 (总RTP: 0.9)
  rtp_6:
    rtp_no: 6
    rtp_value: 0.9
    rtp_components:
      normal_rtp: 0.7 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 58%
      low_multiplier: 0.1106 # 0-1倍 占比 30%
      medium_multiplier: 0.0851 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0013 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 7 (总RTP: 0.91)
  rtp_7:
    rtp_no: 7
    rtp_value: 0.91
    rtp_components:
      normal_rtp: 0.71 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 58%
      low_multiplier: 0.1106 # 0-1倍 占比 30%
      medium_multiplier: 0.0851 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0013 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 8 (总RTP: 0.92)
  rtp_8:
    rtp_no: 8
    rtp_value: 0.92
    rtp_components:
      normal_rtp: 0.72 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 58%
      low_multiplier: 0.1106 # 0-1倍 占比 30%
      medium_multiplier: 0.0851 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0013 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 9 (总RTP: 0.93)
  rtp_9:
    rtp_no: 9
    rtp_value: 0.93
    rtp_components:
      normal_rtp: 0.73 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 55%
      low_multiplier: 0.1103 # 0-1倍 占比 33%
      medium_multiplier: 0.0851 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0016 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 10 (总RTP: 0.94)
  rtp_10:
    rtp_no: 10
    rtp_value: 0.94
    rtp_components:
      normal_rtp: 0.74 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 55%
      low_multiplier: 0.1103 # 0-1倍 占比 33%
      medium_multiplier: 0.0851 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0016 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 11 (总RTP: 0.95)
  rtp_11:
    rtp_no: 11
    rtp_value: 0.95
    rtp_components:
      normal_rtp: 0.75 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 53%
      low_multiplier: 0.1101 # 0-1倍 占比 35%
      medium_multiplier: 0.085 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0018 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 12 (总RTP: 0.96)
  rtp_12:
    rtp_no: 12
    rtp_value: 0.96
    rtp_components:
      normal_rtp: 0.75 # 普通玩法RTP
      special_rtp: 0.21 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 53%
      low_multiplier: 0.1101 # 0-1倍 占比 35%
      medium_multiplier: 0.085 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0018 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 13 (总RTP: 0.97)
  rtp_13:
    rtp_no: 13
    rtp_value: 0.97
    rtp_components:
      normal_rtp: 0.75 # 普通玩法RTP
      special_rtp: 0.22 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.77 # 0倍 占比 51%
      low_multiplier: 0.11 # 0-1倍 占比 37%
      medium_multiplier: 0.0850 # 1-5倍 占比 9%
      high_multiplier: 0.0190 # 5-10倍 占比 2%
      very_high_multiplier: 0.0060 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0080 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0020 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 20 (总RTP: 0.2)
  rtp_20:
    rtp_no: 20
    rtp_value: 0.2
    rtp_components:
      normal_rtp: 0.2 # 普通玩法RTP
      special_rtp: 0.0 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.7781 # 0倍 占比 90%
      low_multiplier: 0.1190 # 0-1倍 占比 8%
      medium_multiplier: 0.0852 # 1-5倍 占比 1.5%
      high_multiplier: 0.0177 # 5-10倍 占比 0.3%
      very_high_multiplier: 0.0 # 10-20倍 占比 0.1%
      mega_multiplier: 0.000 # 20-50倍 占比 0%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 30 (总RTP: 0.3)
  rtp_30:
    rtp_no: 30
    rtp_value: 0.3
    rtp_components:
      normal_rtp: 0.3 # 普通玩法RTP
      special_rtp: 0.0 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.7781 # 0倍 占比 90%
      low_multiplier: 0.1190 # 0-1倍 占比 8%
      medium_multiplier: 0.0852 # 1-5倍 占比 1.5%
      high_multiplier: 0.0177 # 5-10倍 占比 0.3%
      very_high_multiplier: 0.0 # 10-20倍 占比 0.1%
      mega_multiplier: 0.000 # 20-50倍 占比 0%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 40 (总RTP: 0.4)
  rtp_40:
    rtp_no: 40
    rtp_value: 0.4
    rtp_components:
      normal_rtp: 0.4 # 普通玩法RTP
      special_rtp: 0.0 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.7781 # 0倍 占比 90%
      low_multiplier: 0.1190 # 0-1倍 占比 8%
      medium_multiplier: 0.0852 # 1-5倍 占比 1.5%
      high_multiplier: 0.0177 # 5-10倍 占比 0.3%
      very_high_multiplier: 0.0 # 10-20倍 占比 0.1%
      mega_multiplier: 0.000 # 20-50倍 占比 0%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 50 (总RTP: 0.5)
  rtp_50:
    rtp_no: 50
    rtp_value: 0.5
    rtp_components:
      normal_rtp: 0.45 # 普通玩法RTP
      special_rtp: 0.05 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.778 # 0倍 占比 75%
      low_multiplier: 0.1132 # 0-1倍 占比 20%
      medium_multiplier: 0.0852 # 1-5倍 占比 4%
      high_multiplier: 0.0190 # 5-10倍 占比 0.8%
      very_high_multiplier: 0.0046 # 10-20倍 占比 0.2%
      mega_multiplier: 0.000 # 20-50倍 占比 0%
      super_mega_multiplier: 0.000 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.000 # 100-500倍 占比 0.1%

  # 档位 14 (总RTP: 0.98)
  rtp_14:
    rtp_no: 14
    rtp_value: 1.5
    rtp_components:
      normal_rtp: 1.1 # 普通玩法RTP
      special_rtp: 0.4 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.6873 # 0倍 占比 50%
      low_multiplier: 0.1902 # 0-1倍 占比 38%
      medium_multiplier: 0.0600 # 1-5倍 占比 9%
      high_multiplier: 0.0200 # 5-10倍 占比 2%
      very_high_multiplier: 0.0198 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0197 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0020 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.0010 # 100-500倍 占比 0.1%

  # 档位 15 (总RTP: 0.99)
  rtp_15:
    rtp_no: 15
    rtp_value: 2.0
    rtp_components:
      normal_rtp: 1.5 # 普通玩法RTP
      special_rtp: 0.5 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.5739 # 0倍 占比 49%
      low_multiplier: 0.2931 # 0-1倍 占比 39%
      medium_multiplier: 0.0600 # 1-5倍 占比 9%
      high_multiplier: 0.0200 # 5-10倍 占比 2%
      very_high_multiplier: 0.0200 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0281 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0028 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.0022 # 100-500倍 占比 0.1%

  # 档位 120 (总RTP: 1.2)
  rtp_120:
    rtp_no: 120
    rtp_value: 1.2
    rtp_components:
      normal_rtp: 1.0 # 普通玩法RTP
      special_rtp: 0.2 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.6846 # 0倍 占比 40%
      low_multiplier: 0.1980 # 0-1倍 占比 35%
      medium_multiplier: 0.0783 # 1-5倍 占比 15%
      high_multiplier: 0.0219 # 5-10倍 占比 6%
      very_high_multiplier: 0.0150 # 10-20倍 占比 3%
      mega_multiplier: 0.0076 # 20-50倍 占比 0.8%
      super_mega_multiplier: 0.0030 # 50-100倍 占比 0.2%
      ultra_mega_multiplier: 0.00 # 100-500倍 占比 0.1%

  # 档位 150 (总RTP: 1.5)
  rtp_150:
    rtp_no: 150
    rtp_value: 1.5
    rtp_components:
      normal_rtp: 1.2 # 普通玩法RTP
      special_rtp: 0.3 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.6883 # 0倍 占比 50%
      low_multiplier: 0.1901 # 0-1倍 占比 38%
      medium_multiplier: 0.0600 # 1-5倍 占比 9%
      high_multiplier: 0.0201 # 5-10倍 占比 2%
      very_high_multiplier: 0.0198 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0197 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0020 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.00 # 100-500倍 占比 0.1%

  # 档位 200 (总RTP: 2.0)
  rtp_200:
    rtp_no: 200
    rtp_value: 2.0
    rtp_components:
      normal_rtp: 1.5 # 普通玩法RTP
      special_rtp: 0.5 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.6196 # 0倍 占比 49%
      low_multiplier: 0.2349 # 0-1倍 占比 39%
      medium_multiplier: 0.0580 # 1-5倍 占比 9%
      high_multiplier: 0.0366 # 5-10倍 占比 2%
      very_high_multiplier: 0.0200 # 10-20倍 占比 0.8%
      mega_multiplier: 0.0281 # 20-50倍 占比 0.2%
      super_mega_multiplier: 0.0028 # 50-100倍 占比 0%
      ultra_mega_multiplier: 0.00 # 100-500倍 占比 0.1%

  # 档位 300 (总RTP: 3.0)
  rtp_300:
    rtp_no: 300
    rtp_value: 3.0
    rtp_components:
      normal_rtp: 2.3 # 普通玩法RTP
      special_rtp: 0.7 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.6301 # 0倍 占比 25%
      low_multiplier: 0.1392 # 0-1倍 占比 20%
      medium_multiplier: 0.0500 # 1-5倍 占比 30%
      high_multiplier: 0.1293 # 5-10倍 占比 15%
      very_high_multiplier: 0.0180 # 10-20倍 占比 7%
      mega_multiplier: 0.0267 # 20-50倍 占比 2.5%
      super_mega_multiplier: 0.0067 # 50-100倍 占比 0.5%
      ultra_mega_multiplier: 0.00 # 100-500倍 占比 0.1%

  # 档位 500 (总RTP: 5.0)
  rtp_500:
    rtp_no: 500
    rtp_value: 5.0
    rtp_components:
      normal_rtp: 4.0 # 普通玩法RTP
      special_rtp: 1.0 # 特殊玩法RTP
    multiplier_distribution:
      zero_win: 0.5291 # 0倍 占比 15%
      low_multiplier: 0.0919 # 0-1倍 占比 15%
      medium_multiplier: 0.0720 # 1-5倍 占比 35%
      high_multiplier: 0.1943 # 5-10倍 占比 20%
      very_high_multiplier: 0.0569 # 10-20倍 占比 10%
      mega_multiplier: 0.0491 # 20-50倍 占比 4%
      super_mega_multiplier: 0.0067 # 50-100倍 占比 1%
      ultra_mega_multiplier: 0.00 # 100-500倍 占比 0.1%
