-- SQL 建表文件
-- 表名: GameResultData_20064
-- 生成时间: 2025-11-20 20:56:57

CREATE SEQUENCE IF NOT EXISTS "GameResultData_20064_id_seq";

CREATE TABLE IF NOT EXISTS "GameResultData_20064" (
	id INTEGER PRIMARY KEY DEFAULT nextval('"GameResultData_20064_id_seq"'),
	tb DOUBLE PRECISION NOT NULL,
	aw DOUBLE PRECISION NOT NULL,
	gwt INTEGER NOT NULL,
	sp BOOLEAN NOT NULL DEFAULT false,
	fb INTEGER NOT NULL DEFAULT 0,
	gd JSONB,
	"createdAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	"updatedAt" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE "GameResultData_20064"
	ALTER COLUMN id SET DEFAULT nextval('"GameResultData_20064_id_seq"');
